use openrazer::{KeyCode, MatrixMapper};

pub fn create_default_matrix_mapper() -> MatrixMapper {
    let mut matrix_mapper = MatrixMapper::default();
    // NOTE: This is the mapping for my keyboard (Razer Ornata Chroma)
    matrix_mapper.add_mappings([
        // Other
        (KeyCode::KEY_ESC, (1, 0)),
        // Function keys
        (KeyCode::KEY_F1, (3, 0)),
        (KeyCode::KEY_F2, (4, 0)),
        (KeyCode::KEY_F3, (5, 0)),
        (KeyCode::KEY_F4, (6, 0)),
        (KeyCode::KEY_F5, (7, 0)),
        (KeyCode::KEY_F6, (8, 0)),
        (KeyCode::KEY_F7, (9, 0)),
        (KeyCode::KEY_F8, (10, 0)),
        (KeyCode::KEY_F9, (11, 0)),
        (KeyCode::KEY_F10, (12, 0)),
        (KeyCode::KEY_F11, (13, 0)),
        (KeyCode::KEY_F12, (14, 0)),
        // Control keys
        (KeyCode::KEY_SYSRQ, (15, 0)),
        (KeyCode::KEY_SCROLLLOCK, (16, 0)),
        (KeyCode::KEY_PAUSE, (17, 0)),
        (KeyCode::KEY_INSERT, (15, 1)),
        (KeyCode::KEY_HOME, (16, 1)),
        (KeyCode::KEY_PAGEUP, (17, 1)),
        (KeyCode::KEY_DELETE, (15, 2)),
        (KeyCode::KEY_END, (16, 2)),
        (KeyCode::KEY_PAGEDOWN, (17, 2)),
        // Arrow keys
        (KeyCode::KEY_UP, (16, 4)),
        (KeyCode::KEY_LEFT, (15, 5)),
        (KeyCode::KEY_DOWN, (16, 5)),
        (KeyCode::KEY_RIGHT, (17, 5)),
        // Numpad
        (KeyCode::KEY_NUMLOCK, (18, 1)),
        (KeyCode::KEY_KPSLASH, (19, 1)),
        (KeyCode::KEY_KPASTERISK, (20, 1)),
        (KeyCode::KEY_KPMINUS, (21, 1)),
        (KeyCode::KEY_KP7, (18, 2)),
        (KeyCode::KEY_KP8, (19, 2)),
        (KeyCode::KEY_KP9, (20, 2)),
        (KeyCode::KEY_KPPLUS, (21, 2)),
        (KeyCode::KEY_KP4, (18, 3)),
        (KeyCode::KEY_KP5, (19, 3)),
        (KeyCode::KEY_KP6, (20, 3)),
        (KeyCode::KEY_KP1, (18, 4)),
        (KeyCode::KEY_KP2, (19, 4)),
        (KeyCode::KEY_KP3, (20, 4)),
        (KeyCode::KEY_KPENTER, (21, 4)),
        (KeyCode::KEY_KP0, (19, 5)),
        (KeyCode::KEY_KPDOT, (20, 5)),
        // Typewriter A
        (KeyCode::KEY_GRAVE, (1, 1)),
        (KeyCode::KEY_1, (2, 1)),
        (KeyCode::KEY_2, (3, 1)),
        (KeyCode::KEY_3, (4, 1)),
        (KeyCode::KEY_4, (5, 1)),
        (KeyCode::KEY_5, (6, 1)),
        (KeyCode::KEY_6, (7, 1)),
        (KeyCode::KEY_7, (8, 1)),
        (KeyCode::KEY_8, (9, 1)),
        (KeyCode::KEY_9, (10, 1)),
        (KeyCode::KEY_0, (11, 1)),
        (KeyCode::KEY_MINUS, (12, 1)),
        (KeyCode::KEY_EQUAL, (13, 1)),
        (KeyCode::KEY_BACKSPACE, (14, 1)),
        // Typewriter B
        (KeyCode::KEY_TAB, (1, 2)),
        (KeyCode::KEY_Q, (2, 2)),
        (KeyCode::KEY_W, (3, 2)),
        (KeyCode::KEY_E, (4, 2)),
        (KeyCode::KEY_R, (5, 2)),
        (KeyCode::KEY_T, (6, 2)),
        (KeyCode::KEY_Y, (7, 2)),
        (KeyCode::KEY_U, (8, 2)),
        (KeyCode::KEY_I, (9, 2)),
        (KeyCode::KEY_O, (10, 2)),
        (KeyCode::KEY_P, (11, 2)),
        (KeyCode::KEY_LEFTBRACE, (12, 2)),
        (KeyCode::KEY_RIGHTBRACE, (13, 2)),
        (KeyCode::KEY_BACKSLASH, (14, 2)),
        // Typewriter C
        (KeyCode::KEY_CAPSLOCK, (1, 3)),
        (KeyCode::KEY_A, (2, 3)),
        (KeyCode::KEY_S, (3, 3)),
        (KeyCode::KEY_D, (4, 3)),
        (KeyCode::KEY_F, (5, 3)),
        (KeyCode::KEY_G, (6, 3)),
        (KeyCode::KEY_H, (7, 3)),
        (KeyCode::KEY_J, (8, 3)),
        (KeyCode::KEY_K, (9, 3)),
        (KeyCode::KEY_L, (10, 3)),
        (KeyCode::KEY_SEMICOLON, (11, 3)),
        (KeyCode::KEY_APOSTROPHE, (12, 3)),
        (KeyCode::KEY_ENTER, (14, 3)),
        // Typewriter D
        (KeyCode::KEY_LEFTSHIFT, (1, 4)),
        (KeyCode::KEY_Z, (3, 4)),
        (KeyCode::KEY_X, (4, 4)),
        (KeyCode::KEY_C, (5, 4)),
        (KeyCode::KEY_V, (6, 4)),
        (KeyCode::KEY_B, (7, 4)),
        (KeyCode::KEY_N, (8, 4)),
        (KeyCode::KEY_M, (9, 4)),
        (KeyCode::KEY_COMMA, (10, 4)),
        (KeyCode::KEY_DOT, (11, 4)),
        (KeyCode::KEY_SLASH, (12, 4)),
        (KeyCode::KEY_RIGHTSHIFT, (14, 4)),
        // Typewriter E
        (KeyCode::KEY_LEFTCTRL, (1, 5)),
        (KeyCode::KEY_LEFTMETA, (2, 5)),
        (KeyCode::KEY_LEFTALT, (3, 5)),
        (KeyCode::KEY_SPACE, (7, 5)),
        (KeyCode::KEY_RIGHTALT, (11, 5)),
        // NOTE: Not actually accessible with my keyboard, it seems to do some special stuff with
        // it where it allows me to do something like fn+f6 to press the pause/play media button.
        (KeyCode::KEY_FN, (12, 5)),
        (KeyCode::KEY_COMPOSE, (13, 5)),
        (KeyCode::KEY_RIGHTCTRL, (14, 5)),
        // Some extra keys (Media keys that are emulated by my keyboard using fn+f*
        (KeyCode::KEY_MUTE, (3, 0)),
        (KeyCode::KEY_VOLUMEDOWN, (4, 0)),
        (KeyCode::KEY_VOLUMEUP, (5, 0)),
        (KeyCode::KEY_PREVIOUSSONG, (7, 0)),
        (KeyCode::KEY_PLAYPAUSE, (8, 0)),
        (KeyCode::KEY_NEXTSONG, (9, 0)),
        (KeyCode(685), (11, 0)), // No clue what this key does. It toggles a light on my keyboard??
        (KeyCode(684), (12, 0)), // Toggle game mode
        (KeyCode(683), (13, 0)), // Keyboard lighting brightness down
        (KeyCode(682), (14, 0)), // Keyboard lighting brightness up
    ]);
    matrix_mapper
}
